export const home = {
  metadata: {
    title: "Học làm video AI cho người mới bắt đầu | GenYZ Studio",
    description: "Bắt đầu làm video AI cùng GenYZ Studio. Hướng dẫn bằng tiếng Việt, lộ trình dễ hiểu và workshop nhập môn miễn phí dành cho người mới.",
  },
  nav: [
    { label: "Video của studio", href: "#san-pham" },
    { label: "Lộ trình", href: "#lo-trinh" },
    { label: "Workshop miễn phí", href: "#workshop" },
    { label: "Hỏi đáp", href: "#hoi-dap" },
  ],
  hero: {
    eyebrow: "HỌC LÀM VIDEO AI · BẰNG TIẾNG VIỆT",
    title: "Tự tay làm", highlight: "video AI", ending: "đầu tiên.",
    description: "Workshop nhập môn miễn phí, học trực tiếp cùng người hướng dẫn. Bắt đầu từ con số 0, giải thích bằng tiếng Việt.",
    ctaNote: "Miễn phí · Nhận lịch học qua Zalo",
    explore: "Xem video của studio", caption: "PHIM CỦA GENYZ STUDIO",
    filmTitle: "Clever Little Rat", silentExcerpt: "Trích đoạn · Không âm thanh",
    play: "Phát video", pause: "Tạm dừng", fullFilm: "Xem phim đầy đủ",
    playbackError: "Không tải được video. Bạn có thể xem trên YouTube.",
    imageLabel: "Hình minh hoạ tạo bằng AI · Không phải sản phẩm học viên",
    alt: "Khung hình từ phim The Legend of Titus do GenYZ Studio thực hiện: một sinh vật màu xanh trong khu rừng.",
  },
  reassurance: ["Không cần biết lập trình", "Giải thích bằng tiếng Việt", "Học qua từng bước thực hành"],
  outcomes: {
    eyebrow: "BẮT ĐẦU VỚI ĐIỀU BẠN MUỐN KỂ",
    title: "Bạn có ý tưởng.\nAI giúp bạn mở khung hình.",
    description: "Một câu chuyện nhỏ, một sản phẩm yêu thích hay một nơi bạn muốn đến. Học cách biến điều đó thành hình ảnh và chuyển động.",
    items: [
      { title: "Diễn đạt ý tưởng rõ ràng", text: "Biến ý tưởng thành câu lệnh (prompt) dễ hiểu. Biết cần mô tả điều gì để AI đi đúng hướng." },
      { title: "Tạo khung hình có chủ đích", text: "Làm quen với nhân vật, bối cảnh, ánh sáng và góc máy. Nhận ra điều gì cần sửa trong một hình ảnh." },
      { title: "Ghép nên câu chuyện của bạn", text: "Từ hình ảnh đến chuyển động, rồi kết nối các cảnh, âm thanh và phụ đề thành một video ngắn." },
    ],
  },
  process: {
    eyebrow: "HẬU TRƯỜNG · CLEVER LITTLE RAT",
    title: "Một bộ phim AI\nđược làm ra như thế nào.",
    description: "Tài liệu thật từ quá trình làm phim Clever Little Rat của studio. Workshop giúp bạn làm quen với từng công đoạn này ở phiên bản đơn giản hơn.",
    steps: [
      { label: "01 / Khoá nhân vật", title: "Bảng nhân vật", text: "Leo được vẽ từ bốn góc, toàn thân và cận mặt. Mọi cảnh sau đều bám theo bảng này để nhân vật không đổi mặt, đổi áo.", image: "/images/process/leo-character-sheet.webp", width: 1200, height: 800, alt: "Bảng nhân vật Leo: cậu bé áo vàng, quần đen, nhìn từ phía trước, hai bên và phía sau, kèm bốn ảnh cận mặt." },
      { label: "02 / Phân cảnh", title: "Bảng phân cảnh có thời gian", text: "Một đoạn 15 giây được chia thành chín khung, mỗi khung ghi rõ thời điểm, lời thoại và hành động.", image: "/images/process/scene-07-storyboard.webp", width: 1400, height: 933, alt: "Bảng phân cảnh chín khung của cảnh 7, Clever Little Rat: Leo, Mio và Pip trước một đường hầm nhỏ, mỗi khung có mốc thời gian và lời thoại." },
    ],
    promptLabel: "03 / Câu lệnh cho video",
    prompt: "@image2 is Leo's strict identity and wardrobe sheet: small boy, warm peach skin, rosy round cheeks, large brown eyes, short tousled black hair, yellow tee, black cuffed trousers, grey shoes. Preserve exact likeness. No beautification. No deformation. Stable face throughout.",
    promptNote: "Trích câu lệnh thật dùng cho cảnh 7. Câu lệnh mô tả rõ nhân vật và yêu cầu AI giữ nguyên khuôn mặt. Workshop giải thích từng phần bằng tiếng Việt.",
    result: { label: "04 / Phim hoàn chỉnh", title: "Ghép cảnh, âm thanh và phụ đề", text: "Các đoạn video được chọn lọc, dựng nhịp và hoàn thiện thành một tập phim ngắn.", alt: "Khung hình từ phim Clever Little Rat: Through the Button Bridge của GenYZ Studio.", link: "Xem các phim của studio" },
    note: "Tài liệu từ nhiều công đoạn khác nhau của dự án, không phải một cảnh duy nhất. Đây là sản phẩm của studio, không phải bài làm của học viên.",
  },
  journey: {
    title: "Đi từng bước.\nHiểu rồi mới đi tiếp.",
    description: "Lộ trình chương trình đầy đủ, từ làm quen với AI đến hoàn thiện một video ngắn. Workshop miễn phí là bước khởi đầu để bạn trải nghiệm cách học.",
    steps: [
      { title: "Ý tưởng & câu lệnh", tag: "Bắt đầu từ nền tảng", text: "Hiểu AI làm được gì, chọn một ý tưởng vừa sức và viết câu lệnh đầu tiên. Giải thích thuật ngữ tiếng Anh bằng ví dụ tiếng Việt." },
      { title: "Tạo hình ảnh", tag: "Xây dựng khung hình", text: "Mô tả chủ thể, không gian và ánh sáng. Thử chỉnh câu lệnh để hình ảnh gần với ý tưởng hơn, đồng thời giữ nhân vật nhất quán." },
      { title: "Ngôn ngữ điện ảnh", tag: "Kể chuyện bằng góc máy", text: "Làm quen với cỡ cảnh, bố cục và bảng phân cảnh (storyboard). Chia một câu chuyện thành những cảnh dễ thực hiện." },
      { title: "Tạo chuyển động", tag: "Đưa hình ảnh vào video", text: "Thử chuyển hình ảnh thành video. Mô tả chuyển động của nhân vật, máy quay và bối cảnh; nhận biết những lỗi thường gặp." },
      { title: "Hoàn thiện video", tag: "Kết nối thành câu chuyện", text: "Chọn cảnh phù hợp, dựng nhịp kể, thêm âm thanh và phụ đề. Kiểm tra chất lượng trước khi xuất video để chia sẻ." },
    ],
  },
  workshop: {
    eyebrow: "WORKSHOP NHẬP MÔN · MIỄN PHÍ",
    title: "Buổi đầu tiên,\ncó người hướng dẫn.",
    description: "Cùng làm quen với cách tạo video AI trong một buổi học trực tiếp. Hỏi khi chưa hiểu, thử từng bước và tìm ra cách bắt đầu phù hợp với bạn.",
    items: ["Làm quen với quy trình từ ý tưởng đến video", "Thực hành viết câu lệnh cho một cảnh đơn giản", "Trao đổi và gỡ vướng cùng người hướng dẫn"],
    format: "Trực tiếp, có người hướng dẫn",
    pending: "Sẽ thông báo",
    labels: { format: "Hình thức", city: "Địa điểm", venue: "Địa chỉ", date: "Lịch học", duration: "Thời lượng", capacity: "Số chỗ", seats: "người" },
    tuition: "Học phí workshop", price: "Miễn phí",
    interest: "Đăng ký quan tâm chưa đồng nghĩa với xác nhận chỗ học. Lịch, địa điểm và hướng dẫn chuẩn bị sẽ được trao đổi qua Zalo khi có thông tin.",
    costs: "Học phí miễn phí không bao gồm phí thuê bao hoặc lượt tạo của các công cụ AI bên thứ ba. Yêu cầu công cụ sẽ được thông báo trước buổi học.",
  },
  skool: {
    label: "HỌC THEO NHỊP CỦA BẠN", title: "Một không gian để tiếp tục học.",
    description: "Khoá học tự học trên Skool đang được chuẩn bị. Bạn sẽ có thêm lựa chọn để xem lại, thực hành và tiếp tục khám phá sau workshop.",
    availableDescription: "Khám phá nội dung, hình thức học và điều kiện tham gia trực tiếp trên trang Skool của chương trình.",
    soon: "Sắp ra mắt", link: "Khám phá trên Skool",
  },
  faq: {
    title: "Bạn đang băn khoăn?", description: "Bắt đầu một điều mới luôn có nhiều câu hỏi. Đây là những điều bạn cần biết trước khi tham gia.",
    items: [
      { question: "Tôi chưa từng dùng AI. Có học được không?", answer: "Có. Workshop nhập môn dành cho người mới bắt đầu. Bạn sẽ được làm quen với quy trình, thuật ngữ và cách viết câu lệnh qua ví dụ đơn giản. Không cần biết lập trình hay có kinh nghiệm làm phim." },
      { question: "Tiếng Anh của tôi chưa tốt thì sao?", answer: "Nội dung được giải thích bằng tiếng Việt. Tên công cụ và một số nút bấm vẫn có thể hiển thị bằng tiếng Anh; chúng sẽ được giải thích theo ngữ cảnh. Bạn sẽ học cách hiểu và điều chỉnh câu lệnh, không chỉ sao chép những đoạn tiếng Anh khó hiểu." },
      { question: "Tôi cần chuẩn bị thiết bị gì?", answer: "Nên có laptop kết nối Internet để thuận tiện thực hành. Danh sách tài khoản và công cụ cần dùng sẽ được thông báo trước buổi học. Đừng vội mua thiết bị hoặc đăng ký gói công cụ trả phí chỉ để chuẩn bị." },
      { question: "Workshop miễn phí có bao gồm phí công cụ AI không?", answer: "Không. Miễn phí ở đây là học phí buổi workshop nhập môn. Một số công cụ AI có thể giới hạn lượt dùng miễn phí hoặc yêu cầu trả phí. Các yêu cầu và chi phí liên quan sẽ được thông báo trước để bạn cân nhắc." },
      { question: "Workshop tổ chức ở đâu, khi nào?", answer: "Thông tin mới nhất nằm trong mục Workshop trên trang này. Nếu hiển thị “Sẽ thông báo”, lịch hoặc địa điểm chưa được xác nhận. Bạn có thể đăng ký quan tâm qua Zalo để trao đổi khi có lịch phù hợp." },
      { question: "Nhắn Zalo có nghĩa là tôi đã giữ được chỗ chưa?", answer: "Chưa. Tin nhắn Zalo là bước đăng ký quan tâm. Chỗ học chỉ được xác nhận sau khi bạn và người hướng dẫn thống nhất buổi học cụ thể." },
      { question: "Workshop có dạy toàn bộ lộ trình không?", answer: "Workshop là buổi trải nghiệm nhập môn, tập trung vào cách bắt đầu. Lộ trình đầy đủ trên trang mô tả hướng học dài hơn. Khoá tự học trên Skool là lựa chọn riêng; thông tin sẽ được cập nhật khi sẵn sàng." },
    ],
  },
  contact: {
    title: "Ý tưởng đầu tiên\ncủa bạn là gì?", description: "Bắt đầu bằng một cuộc trò chuyện. Kể cho GenYZ Studio điều bạn muốn làm với video AI.",
    cta: "Đăng ký quan tâm qua Zalo", unavailable: "Đăng ký sẽ mở sớm",
    qrAlt: "Mã QR liên hệ GenYZ Studio qua Zalo", qrLabel: "Quét mã để mở Zalo",
    accountNote: "Bạn sẽ trao đổi với người phụ trách workshop qua Zalo.",
  },
  footer: { description: "Học cách kể câu chuyện của bạn bằng AI.", note: "Dành cho người mới. Hướng dẫn bằng tiếng Việt.", back: "Về đầu trang", rights: "GenYZ Studio", skip: "Bỏ qua menu, đến nội dung" },
};
