import type { home } from './home';

export const homeEn: typeof home = {
  metadata: { title: 'AI Video Creation Training for Beginners | GenYZ Studio', description: 'Learn AI video creation with GenYZ Studio. Explore prompts, images, motion and editing through an introductory workshop taught in Vietnamese.' },
  nav: [{ label: 'Studio films', href: '#san-pham' }, { label: 'Intro workshop', href: '#workshop' }, { label: 'Learning path', href: '#lo-trinh' }, { label: 'FAQs', href: '#hoi-dap' }],
  hero: { title: 'Create your first AI video.', description: 'An introductory workshop, taught in person with a guide. Start from zero, with explanations in Vietnamese.', ctaNote: 'The schedule is sent on Zalo.', turnaround: { alt: 'Leo, the lead character of Clever Little Rat, seen from the front, left, back and right.', caption: 'Leo is designed from four angles before he appears on screen. This is the real character sheet from Clever Little Rat.' }, caption: 'Films by GenYZ Studio', silentExcerpt: 'Silent excerpt', play: 'Play video', pause: 'Pause', fullFilm: 'Watch the full film', playbackError: 'The video could not load. You can watch it on YouTube.' },
  reassurance: ['No coding experience needed', 'Explanations in Vietnamese', 'Learn through guided practice'],
  outcomes: { title: 'You have an idea.\nAI helps you picture it.', description: 'A short story, a favourite product or a place you want to visit. Learn to turn your ideas into images and motion.', items: [{ title: 'Express your ideas clearly', text: 'Turn an idea into a clear prompt. Learn which details help guide the AI towards your intention.' }, { title: 'Create images with purpose', text: 'Explore characters, settings, lighting and camera angles. Learn to spot what needs improving in an image.' }, { title: 'Put your story together', text: 'Move from still images to motion, then combine scenes, sound and subtitles into a short video.' }] },
  process: {
    title: 'One shot,\nfrom prompt to film.',
    description: 'Follow one 5-second shot from Clever Little Rat: Through the Button Bridge, as Pip crosses the button bridge. Every step is real studio material for the same shot. The workshop introduces each step in a simpler form.',
    prompt: { label: 'The prompt', text: 'The real prompt for scene 6, shot 2. It describes the action, camera, dialogue and sound. The workshop explains each part in Vietnamese.', body: 'Create a 5-second 16:9 cinematic 3D animated children’s film clip. Pip easily crosses the colorful button bridge with confident tiny steps. He reaches the other side, turns around, and waves proudly to Leo and Mio. Camera: side tracking shot following Pip across the bridge, low to bridge level.' },
    blocking: { label: '3D blocking', title: 'Block it out before rendering', text: 'Simple shapes mark the bridge, where the characters stand and how the camera moves, so the layout can be checked before generating video.', src: '/media/process/s06-shot02-blocking.mp4', poster: '/media/process/s06-shot02-blocking.webp', alt: '3D blocking for scene 6, shot 2: coloured discs stand in for the button bridge and a green block stands in for Pip.' },
    plan: { label: 'Shot plan', title: 'Four cuts in five seconds', text: 'Each cut lists its timing, action, dialogue and sound, with a camera-path diagram and reference images of Leo, Mio and Pip.', image: '/images/process/s06-shot02-plan.webp', width: 1400, height: 933, alt: 'Layout study for scene 6, shot 2: four timed cuts with camera notes, dialogue, sound, character references and a top-down camera path.' },
    shot: { label: 'AI-generated shot', title: 'Pip crosses the bridge', text: 'The 5-second clip for this shot, generated with AI from the locked characters and set.', src: '/media/process/s06-shot02-shot.mp4', poster: '/media/process/s06-shot02-shot.webp', alt: 'AI-generated clip: Pip the mouse in a lime vest steps across giant buttons onto the bank.' },
    result: { label: 'In the finished film', title: 'Through the Button Bridge', text: 'Scene 6 became a 45-second episode, public on YouTube and TikTok since 20 September 2026.', alt: 'A frame from Clever Little Rat: Through the Button Bridge by GenYZ Studio.', link: 'Watch it in the gallery' },
    note: 'All studio work for the same shot, not student work.',
  },
  wip: {
    title: 'In progress:\nCoco and Pip at the farm.',
    description: 'An unreleased project made across two tools. The shot plan was made in OpenArt and the shots were generated in Google Flow. The story: Coco the rooster has lost his golden whistle, and the farm is stuck in a long night with no sunrise.',
    board: { label: 'Shot plan', meta: 'OpenArt', title: 'Five cuts for one scene', text: 'Each cut lists its lens, duration and camera move. The board also has character references, a top-down set plan and lighting notes.', image: '/images/process/coco-pip-farm-board.webp', width: 1400, height: 933, alt: 'OpenArt shot plan for EXT. THE FARM: Coco and Pip character references, a farm floor plan, five storyboard frames with lens and duration, and lighting notes.' },
    clips: [
      { label: 'Beat 1', meta: 'Google Flow', title: 'Pip bursts out of the hay', text: 'The same story beat as cut 1 on the board: Pip arrives and skids to a stop in front of Coco.', src: '/media/process/coco-pip-cut1-pip.mp4', poster: '/media/process/coco-pip-cut1-pip.webp', alt: 'AI-generated shot in Google Flow: Pip the hamster in an explorer hat stands before Coco the rooster, wings spread, in a farmyard at night.' },
      { label: 'Beat 3', meta: 'Google Flow', title: 'Coco tells of the golden whistle', text: 'The same story beat as cut 3 on the board, framed as a medium shot instead of a close-up.', src: '/media/process/coco-pip-cut3-coco.mp4', poster: '/media/process/coco-pip-cut3-coco.webp', alt: 'AI-generated shot in Google Flow: Coco the rooster stands in the farmyard at 2:30 a.m., gesturing at the dark sky.' },
    ],
    note: 'The Google Flow shots were generated on 6 July 2026, before the OpenArt shot plan was redrawn on 21 July 2026. Studio work, not yet released.',
  },
  journey: { title: 'One step at a time.\nUnderstand before moving on.', description: 'The broader programme covers the journey from understanding AI to finishing a short video. The intro workshop is an introduction to this way of learning.', workshopTag: 'Covered in the intro workshop', steps: [{ inWorkshop: true, title: 'Ideas & prompts', tag: 'Start with the basics', text: 'Understand what AI can do, choose a manageable idea and write your first prompt. English terms are explained through Vietnamese examples.' }, { inWorkshop: false, title: 'Image creation', tag: 'Build the frame', text: 'Describe your subject, setting and lighting. Refine prompts to get closer to your idea while keeping characters consistent.' }, { inWorkshop: false, title: 'The language of film', tag: 'Tell stories through the camera', text: 'Explore shot sizes, composition and storyboards. Break a story into scenes you can create.' }, { inWorkshop: false, title: 'Creating motion', tag: 'Bring images into video', text: 'Try turning an image into a video. Describe character, camera and background motion, and recognise common issues.' }, { inWorkshop: false, title: 'Finishing your video', tag: 'Connect the story', text: 'Choose your scenes, shape the rhythm, and add sound and subtitles. Check the result before exporting it to share.' }] },
  workshop: { title: 'Your first session,\nwith an instructor.', description: 'Explore AI video creation in an in-person session taught in Vietnamese. Ask questions, try each step and find a starting point that works for you.', items: ['Explore the workflow from idea to video', 'Practise writing a prompt for a simple scene', 'Ask questions and work through challenges with an instructor'], format: 'In person, instructor led, in Vietnamese', pending: 'To be announced', labels: { format: 'Format', city: 'Location', venue: 'Venue', date: 'Schedule', duration: 'Duration', capacity: 'Capacity', seats: 'people' }, tuition: 'Workshop tuition', price: 'Free', interest: 'Expressing interest does not confirm a seat. The schedule, location and preparation details will be discussed through Zalo when available.', costs: 'Free tuition does not include subscriptions or generation credits for third-party AI tools. Tool requirements will be shared before the workshop.' },
  instructor: { title: 'Your instructor', photoAlt: 'Photo of the workshop instructor' },
  skool: { title: 'A place to keep learning.', description: 'A self-paced Skool course is in preparation. It will offer another way to review, practise and continue exploring after the workshop.', availableDescription: 'Explore the programme content, learning format and participation requirements on its Skool page.', soon: 'Coming soon', link: 'Explore on Skool' },
  faq: { title: 'Have a question?', description: 'Starting something new brings questions. Here is what to know before joining.', items: [
    { question: 'Can I join if I have never used AI?', answer: 'Yes. The introductory workshop is designed for beginners. You will explore the workflow, terminology and prompting through simple examples. No coding or filmmaking experience is required.' },
    { question: 'What language is the workshop taught in?', answer: 'Teaching is in Vietnamese. Tool names and some buttons may be in English, and the instructor explains them in context. You will learn to understand and adapt prompts, rather than simply copying unfamiliar English text. This English website does not mean English-language teaching is available.' },
    { question: 'What equipment should I bring?', answer: 'A laptop with an Internet connection is recommended for practice. Required accounts and tools will be shared before the session. There is no need to buy equipment or paid subscriptions in advance.' },
    { question: 'Does the workshop include AI tool costs?', answer: 'No. The introductory workshop has no tuition fee, but AI tool costs are separate. Some AI tools limit free usage or require payment. Requirements and related costs will be shared in advance so you can decide.' },
    { question: 'Where and when is the workshop?', answer: 'Check the Workshop section for the latest details. If it says “To be announced”, the date or location is not confirmed. You can express interest through Zalo to discuss a suitable session when dates are available.' },
    { question: 'Does messaging on Zalo reserve my place?', answer: 'No. A Zalo message expresses interest. Your place is confirmed only after you and the instructor agree on a specific session.' },
    { question: 'Does the workshop cover the whole learning path?', answer: 'The workshop is an introductory experience focused on getting started. The full learning path describes a longer programme. The self-paced Skool course is a separate option; details will be updated when it is ready.' }
  ] },
  contact: { title: 'What is your\nfirst idea?', description: 'Start with a conversation. Tell GenYZ Studio what you would like to create with AI video.', cta: 'Express interest via Zalo', unavailable: 'Registration opens soon', qrAlt: 'QR code to contact GenYZ Studio on Zalo', qrLabel: 'Scan to open Zalo', accountNote: 'You will speak with the workshop organiser on Zalo.' },
  footer: { description: 'Learn to tell your story with AI.', note: 'For beginners. Instruction in Vietnamese.', back: 'Back to top', rights: 'GenYZ Studio', skip: 'Skip navigation, go to content' }
};
