import type { home } from './home';

export const homeEn: typeof home = {
  metadata: { title: 'AI Video Creation Training for Beginners | GenYZ Studio', description: 'Learn AI video creation with GenYZ Studio. Explore prompts, images, motion and editing through a free introductory workshop taught in Vietnamese.' },
  nav: [{ label: 'Studio films', href: '#san-pham' }, { label: 'Learning path', href: '#lo-trinh' }, { label: 'Free workshop', href: '#workshop' }, { label: 'FAQs', href: '#hoi-dap' }],
  hero: { eyebrow: 'LEARN AI VIDEO CREATION · TAUGHT IN VIETNAMESE', title: 'Create your first', highlight: 'AI video.', ending: 'Start here.', description: 'A free introductory workshop, taught in person with a guide. Start from zero, with explanations in Vietnamese.', ctaNote: 'Free · Get the schedule on Zalo', explore: 'Explore studio films', caption: 'FILMS BY GENYZ STUDIO', filmTitle: 'Clever Little Rat', silentExcerpt: 'Excerpt · No sound', play: 'Play video', pause: 'Pause', fullFilm: 'Watch the full film', playbackError: 'The video could not load. You can watch it on YouTube.', imageLabel: 'AI-generated illustration · Not student work', alt: 'A frame from The Legend of Titus by GenYZ Studio: a blue creature in a forest.' },
  reassurance: ['No coding experience needed', 'Explanations in Vietnamese', 'Learn through guided practice'],
  outcomes: { eyebrow: 'START WITH THE STORY YOU WANT TO TELL', title: 'You have an idea.\nAI helps you picture it.', description: 'A short story, a favourite product or a place you want to visit. Learn to turn your ideas into images and motion.', items: [{ title: 'Express your ideas clearly', text: 'Turn an idea into a clear prompt. Learn which details help guide the AI towards your intention.' }, { title: 'Create images with purpose', text: 'Explore characters, settings, lighting and camera angles. Learn to spot what needs improving in an image.' }, { title: 'Put your story together', text: 'Move from still images to motion, then combine scenes, sound and subtitles into a short video.' }] },
  process: {
    eyebrow: 'BEHIND THE SCENES · CLEVER LITTLE RAT',
    title: 'How an AI film\nis actually made.',
    description: 'Real production material from the studio’s Clever Little Rat series. The workshop introduces each of these stages in a simpler form.',
    steps: [
      { label: '01 / Lock the character', title: 'Character sheet', text: 'Leo is drawn from four angles, full body and close-up. Every later scene follows this sheet so his face and clothes stay consistent.', image: '/images/process/leo-character-sheet.webp', width: 1200, height: 800, alt: 'Character sheet for Leo: a boy in a yellow tee and black trousers, seen from the front, both sides and the back, with four matching close-ups.' },
      { label: '02 / Storyboard', title: 'A timed storyboard', text: 'A 15-second sequence is split into nine panels, each with its timing, dialogue and action.', image: '/images/process/scene-07-storyboard.webp', width: 1400, height: 933, alt: 'Nine-panel storyboard for Clever Little Rat scene 7: Leo, Mio and Pip at a tiny tunnel, each panel labelled with timing and dialogue.' },
    ],
    promptLabel: '03 / The video prompt',
    prompt: "@image2 is Leo's strict identity and wardrobe sheet: small boy, warm peach skin, rosy round cheeks, large brown eyes, short tousled black hair, yellow tee, black cuffed trousers, grey shoes. Preserve exact likeness. No beautification. No deformation. Stable face throughout.",
    promptNote: 'An excerpt from the real prompt used for scene 7. It describes the character precisely and tells the AI to keep the face stable. The workshop explains each part in Vietnamese.',
    result: { label: '04 / The finished film', title: 'Edit scenes, sound and subtitles', text: 'Video clips are selected, paced and finished into a short episode.', alt: 'A frame from Clever Little Rat: Through the Button Bridge by GenYZ Studio.', link: 'Watch the studio films' },
    note: 'Material from different stages of the project, not a single scene. These are studio productions, not student work.',
  },
  journey: { title: 'One step at a time.\nUnderstand before moving on.', description: 'The broader programme covers the journey from understanding AI to finishing a short video. The free workshop is an introduction to this way of learning.', steps: [{ title: 'Ideas & prompts', tag: 'Start with the basics', text: 'Understand what AI can do, choose a manageable idea and write your first prompt. English terms are explained through Vietnamese examples.' }, { title: 'Image creation', tag: 'Build the frame', text: 'Describe your subject, setting and lighting. Refine prompts to get closer to your idea while keeping characters consistent.' }, { title: 'The language of film', tag: 'Tell stories through the camera', text: 'Explore shot sizes, composition and storyboards. Break a story into scenes you can create.' }, { title: 'Creating motion', tag: 'Bring images into video', text: 'Try turning an image into a video. Describe character, camera and background motion, and recognise common issues.' }, { title: 'Finishing your video', tag: 'Connect the story', text: 'Choose your scenes, shape the rhythm, and add sound and subtitles. Check the result before exporting it to share.' }] },
  workshop: { eyebrow: 'INTRODUCTORY WORKSHOP · FREE', title: 'Your first session,\nwith an instructor.', description: 'Explore AI video creation in an in-person session taught in Vietnamese. Ask questions, try each step and find a starting point that works for you.', items: ['Explore the workflow from idea to video', 'Practise writing a prompt for a simple scene', 'Ask questions and work through challenges with an instructor'], format: 'In person, instructor led · Vietnamese', pending: 'To be announced', labels: { format: 'Format', city: 'Location', venue: 'Venue', date: 'Schedule', duration: 'Duration', capacity: 'Capacity', seats: 'people' }, tuition: 'Workshop tuition', price: 'Free', interest: 'Expressing interest does not confirm a seat. The schedule, location and preparation details will be discussed through Zalo when available.', costs: 'Free tuition does not include subscriptions or generation credits for third-party AI tools. Tool requirements will be shared before the workshop.' },
  skool: { label: 'LEARN AT YOUR OWN PACE', title: 'A place to keep learning.', description: 'A self-paced Skool course is in preparation. It will offer another way to review, practise and continue exploring after the workshop.', availableDescription: 'Explore the programme content, learning format and participation requirements on its Skool page.', soon: 'Coming soon', link: 'Explore on Skool' },
  faq: { title: 'Have a question?', description: 'Starting something new brings questions. Here is what to know before joining.', items: [
    { question: 'Can I join if I have never used AI?', answer: 'Yes. The introductory workshop is designed for beginners. You will explore the workflow, terminology and prompting through simple examples. No coding or filmmaking experience is required.' },
    { question: 'What language is the workshop taught in?', answer: 'Teaching is in Vietnamese. Tool names and some buttons may be in English, and the instructor explains them in context. You will learn to understand and adapt prompts, rather than simply copying unfamiliar English text. This English website does not mean English-language teaching is available.' },
    { question: 'What equipment should I bring?', answer: 'A laptop with an Internet connection is recommended for practice. Required accounts and tools will be shared before the session. There is no need to buy equipment or paid subscriptions in advance.' },
    { question: 'Does the free workshop include AI tool costs?', answer: 'No. Free refers to tuition for the introductory workshop. Some AI tools limit free usage or require payment. Requirements and related costs will be shared in advance so you can decide.' },
    { question: 'Where and when is the workshop?', answer: 'Check the Workshop section for the latest details. If it says “To be announced”, the date or location is not confirmed. You can express interest through Zalo to discuss a suitable session when dates are available.' },
    { question: 'Does messaging on Zalo reserve my place?', answer: 'No. A Zalo message expresses interest. Your place is confirmed only after you and the instructor agree on a specific session.' },
    { question: 'Does the workshop cover the whole learning path?', answer: 'The workshop is an introductory experience focused on getting started. The full learning path describes a longer programme. The self-paced Skool course is a separate option; details will be updated when it is ready.' }
  ] },
  contact: { title: 'What is your\nfirst idea?', description: 'Start with a conversation. Tell GenYZ Studio what you would like to create with AI video.', cta: 'Express interest via Zalo', unavailable: 'Registration opens soon', qrAlt: 'QR code to contact GenYZ Studio on Zalo', qrLabel: 'Scan to open Zalo', accountNote: 'You will speak with the workshop organiser on Zalo.' },
  footer: { description: 'Learn to tell your story with AI.', note: 'For beginners. Instruction in Vietnamese.', back: 'Back to top', rights: 'GenYZ Studio', skip: 'Skip navigation, go to content' }
};
