export const home = {
  metadata: {
    title: "Học làm video AI cho người mới bắt đầu | GenYZ Studio",
    description: "Bắt đầu làm video AI cùng GenYZ Studio. Hướng dẫn bằng tiếng Việt, lộ trình dễ hiểu và workshop nhập môn dành cho người mới.",
  },
  nav: [
    { label: "Video của studio", href: "#san-pham" },
    { label: "Workshop nhập môn", href: "#workshop" },
    { label: "Lộ trình", href: "#lo-trinh" },
    { label: "Hỏi đáp", href: "#hoi-dap" },
  ],
  hero: {
    title: "Tự tay làm video AI đầu tiên.",
    description: "Workshop nhập môn, học trực tiếp cùng người hướng dẫn. Bắt đầu từ con số 0, giải thích bằng tiếng Việt.",
    ctaNote: "Lịch học được gửi qua Zalo.",
    turnaround: { alt: "Leo, nhân vật chính của phim Clever Little Rat, nhìn từ phía trước, bên trái, phía sau và bên phải.", caption: "Leo được thiết kế từ bốn góc trước khi lên phim. Đây là bảng nhân vật thật của Clever Little Rat." },
    caption: "Phim của GenYZ Studio",
    silentExcerpt: "Trích đoạn không có âm thanh",
    play: "Phát video", pause: "Tạm dừng", fullFilm: "Xem phim đầy đủ",
    playbackError: "Không tải được video. Bạn có thể xem trên YouTube.",
  },
  reassurance: ["Không cần biết lập trình", "Giải thích bằng tiếng Việt", "Học qua từng bước thực hành"],
  outcomes: {
    title: "Bạn có ý tưởng.\nAI giúp bạn mở khung hình.",
    description: "Một câu chuyện nhỏ, một sản phẩm yêu thích hay một nơi bạn muốn đến. Học cách biến điều đó thành hình ảnh và chuyển động.",
    items: [
      { title: "Diễn đạt ý tưởng rõ ràng", text: "Biến ý tưởng thành câu lệnh (prompt) dễ hiểu. Biết cần mô tả điều gì để AI đi đúng hướng." },
      { title: "Tạo khung hình có chủ đích", text: "Làm quen với nhân vật, bối cảnh, ánh sáng và góc máy. Nhận ra điều gì cần sửa trong một hình ảnh." },
      { title: "Ghép nên câu chuyện của bạn", text: "Từ hình ảnh đến chuyển động, rồi kết nối các cảnh, âm thanh và phụ đề thành một video ngắn." },
    ],
  },
  process: {
    title: "Một cảnh quay,\ntừ câu lệnh đến phim.",
    description: "Theo dõi một cảnh dài 5 giây trong phim Clever Little Rat: Through the Button Bridge, khi Pip băng qua cây cầu cúc áo. Mọi bước đều là tài liệu thật của studio cho cùng một cảnh. Workshop giúp bạn làm quen với từng bước ở phiên bản đơn giản hơn.",
    prompt: { label: "Câu lệnh", text: "Câu lệnh thật cho cảnh 6, shot 2. Câu lệnh mô tả hành động, góc máy, lời thoại và âm thanh. Workshop giải thích từng phần bằng tiếng Việt.", body: "Create a 5-second 16:9 cinematic 3D animated children’s film clip. Pip easily crosses the colorful button bridge with confident tiny steps. He reaches the other side, turns around, and waves proudly to Leo and Mio. Camera: side tracking shot following Pip across the bridge, low to bridge level." },
    blocking: { label: "Bố cục 3D", title: "Dựng khối trước khi tạo hình", text: "Những khối hình đơn giản đánh dấu cây cầu, vị trí nhân vật và đường đi của máy quay, để kiểm tra bố cục trước khi tạo video.", src: "/media/process/s06-shot02-blocking.mp4", poster: "/media/process/s06-shot02-blocking.webp", alt: "Bản dựng khối 3D của cảnh 6, shot 2: các đĩa màu tượng trưng cho cây cầu cúc áo và một khối xanh tượng trưng cho Pip." },
    plan: { label: "Kế hoạch cảnh quay", title: "Bốn nhịp cắt trong năm giây", text: "Mỗi nhịp ghi rõ thời điểm, hành động, lời thoại và âm thanh, kèm sơ đồ đường máy quay và ảnh tham chiếu của Leo, Mio và Pip.", image: "/images/process/s06-shot02-plan.webp", width: 1400, height: 933, alt: "Bảng nghiên cứu bố cục cảnh 6, shot 2: bốn khung cắt có mốc thời gian, mô tả máy quay, lời thoại, âm thanh, ảnh tham chiếu nhân vật và sơ đồ đường máy quay." },
    shot: { label: "Cảnh quay tạo bằng AI", title: "Pip băng qua cây cầu", text: "Đoạn video 5 giây của cảnh này, tạo bằng AI theo nhân vật và bối cảnh đã khoá.", src: "/media/process/s06-shot02-shot.mp4", poster: "/media/process/s06-shot02-shot.webp", alt: "Đoạn video tạo bằng AI: chú chuột Pip mặc áo xanh lá bước qua những chiếc cúc áo khổng lồ để lên bờ." },
    result: { label: "Trong phim hoàn chỉnh", title: "Through the Button Bridge", text: "Cảnh 6 được dựng thành tập phim 45 giây, công khai trên YouTube và TikTok từ ngày 20/9/2026.", alt: "Khung hình từ phim Clever Little Rat: Through the Button Bridge của GenYZ Studio.", link: "Xem phim trong thư viện" },
    note: "Tất cả là sản phẩm của studio cho cùng một cảnh, không phải bài làm của học viên.",
  },
  journey: {
    title: "Đi từng bước.\nHiểu rồi mới đi tiếp.",
    description: "Lộ trình chương trình đầy đủ, từ làm quen với AI đến hoàn thiện một video ngắn. Workshop nhập môn là bước khởi đầu để bạn trải nghiệm cách học.",
    workshopTag: "Có trong workshop nhập môn",
    steps: [
      { inWorkshop: true, title: "Ý tưởng & câu lệnh", tag: "Bắt đầu từ nền tảng", text: "Hiểu AI làm được gì, chọn một ý tưởng vừa sức và viết câu lệnh đầu tiên. Giải thích thuật ngữ tiếng Anh bằng ví dụ tiếng Việt." },
      { inWorkshop: false, title: "Tạo hình ảnh", tag: "Xây dựng khung hình", text: "Mô tả chủ thể, không gian và ánh sáng. Thử chỉnh câu lệnh để hình ảnh gần với ý tưởng hơn, đồng thời giữ nhân vật nhất quán." },
      { inWorkshop: false, title: "Ngôn ngữ điện ảnh", tag: "Kể chuyện bằng góc máy", text: "Làm quen với cỡ cảnh, bố cục và bảng phân cảnh (storyboard). Chia một câu chuyện thành những cảnh dễ thực hiện." },
      { inWorkshop: false, title: "Tạo chuyển động", tag: "Đưa hình ảnh vào video", text: "Thử chuyển hình ảnh thành video. Mô tả chuyển động của nhân vật, máy quay và bối cảnh; nhận biết những lỗi thường gặp." },
      { inWorkshop: false, title: "Hoàn thiện video", tag: "Kết nối thành câu chuyện", text: "Chọn cảnh phù hợp, dựng nhịp kể, thêm âm thanh và phụ đề. Kiểm tra chất lượng trước khi xuất video để chia sẻ." },
    ],
  },
  workshop: {
    title: "Buổi đầu tiên,\ncó người hướng dẫn.",
    description: "Cùng làm quen với cách tạo video AI trong một buổi học trực tiếp. Hỏi khi chưa hiểu, thử từng bước và tìm ra cách bắt đầu phù hợp với bạn.",
    items: ["Làm quen với quy trình từ ý tưởng đến video", "Thực hành viết câu lệnh cho một cảnh đơn giản", "Trao đổi và gỡ vướng cùng người hướng dẫn"],
    format: "Trực tiếp, có người hướng dẫn",
    pending: "Sẽ thông báo",
    labels: { format: "Hình thức", city: "Địa điểm", venue: "Địa chỉ", date: "Lịch học", duration: "Thời lượng", capacity: "Số chỗ", seats: "người" },
    tuition: "Học phí workshop", price: "Miễn phí",
    interest: "Đăng ký quan tâm chưa đồng nghĩa với xác nhận chỗ học. Lịch, địa điểm và hướng dẫn chuẩn bị sẽ được trao đổi qua Zalo khi có thông tin.",
    costs: "Workshop không thu học phí, nhưng chưa bao gồm phí thuê bao hoặc lượt tạo của các công cụ AI bên thứ ba. Yêu cầu công cụ sẽ được thông báo trước buổi học.",
  },
  instructor: { title: "Người hướng dẫn", photoAlt: "Ảnh người hướng dẫn workshop" },
  skool: {
    title: "Một không gian để tiếp tục học.",
    description: "Khoá học tự học trên Skool đang được chuẩn bị. Bạn sẽ có thêm lựa chọn để xem lại, thực hành và tiếp tục khám phá sau workshop.",
    availableDescription: "Khám phá nội dung, hình thức học và điều kiện tham gia trực tiếp trên trang Skool của chương trình.",
    soon: "Sắp ra mắt", link: "Khám phá trên Skool",
  },
  faq: {
    title: "Bạn đang băn khoăn?", description: "Bắt đầu một điều mới luôn có nhiều câu hỏi. Đây là những điều bạn cần biết trước khi tham gia.",
    items: [
      { question: "Tôi chưa từng dùng AI. Có học được không?", answer: "Có. Workshop nhập môn dành cho người mới bắt đầu. Bạn sẽ được làm quen với quy trình, thuật ngữ và cách viết câu lệnh qua ví dụ đơn giản. Không cần biết lập trình hay có kinh nghiệm làm phim." },
      { question: "Tiếng Anh của tôi chưa tốt thì sao?", answer: "Nội dung được giải thích bằng tiếng Việt. Tên công cụ và một số nút bấm vẫn có thể hiển thị bằng tiếng Anh; chúng sẽ được giải thích theo ngữ cảnh. Bạn sẽ học cách hiểu và điều chỉnh câu lệnh, không chỉ sao chép những đoạn tiếng Anh khó hiểu." },
      { question: "Tôi cần chuẩn bị thiết bị gì?", answer: "Nên có laptop kết nối Internet để thuận tiện thực hành. Danh sách tài khoản và công cụ cần dùng sẽ được thông báo trước buổi học. Đừng vội mua thiết bị hoặc đăng ký gói công cụ trả phí chỉ để chuẩn bị." },
      { question: "Workshop có bao gồm phí công cụ AI không?", answer: "Không. Workshop nhập môn không thu học phí, nhưng phí công cụ AI là riêng. Một số công cụ AI có thể giới hạn lượt dùng miễn phí hoặc yêu cầu trả phí. Các yêu cầu và chi phí liên quan sẽ được thông báo trước để bạn cân nhắc." },
      { question: "Workshop tổ chức ở đâu, khi nào?", answer: "Thông tin mới nhất nằm trong mục Workshop trên trang này. Nếu hiển thị “Sẽ thông báo”, lịch hoặc địa điểm chưa được xác nhận. Bạn có thể đăng ký quan tâm qua Zalo để trao đổi khi có lịch phù hợp." },
      { question: "Nhắn Zalo có nghĩa là tôi đã giữ được chỗ chưa?", answer: "Chưa. Tin nhắn Zalo là bước đăng ký quan tâm. Chỗ học chỉ được xác nhận sau khi bạn và người hướng dẫn thống nhất buổi học cụ thể." },
      { question: "Workshop có dạy toàn bộ lộ trình không?", answer: "Workshop là buổi trải nghiệm nhập môn, tập trung vào cách bắt đầu. Lộ trình đầy đủ trên trang mô tả hướng học dài hơn. Khoá tự học trên Skool là lựa chọn riêng; thông tin sẽ được cập nhật khi sẵn sàng." },
    ],
  },
  contact: {
    title: "Ý tưởng đầu tiên\ncủa bạn là gì?", description: "Bắt đầu bằng một cuộc trò chuyện. Kể cho GenYZ Studio điều bạn muốn làm với video AI.",
    cta: "Đăng ký quan tâm qua Zalo", unavailable: "Đăng ký sẽ mở sớm",
    qrAlt: "Mã QR liên hệ GenYZ Studio qua Zalo", qrLabel: "Quét mã để mở Zalo",
    accountNote: "Bạn sẽ trao đổi với người phụ trách workshop qua Zalo.",
  },
  footer: { description: "Học cách kể câu chuyện của bạn bằng AI.", note: "Dành cho người mới. Hướng dẫn bằng tiếng Việt.", back: "Về đầu trang", rights: "GenYZ Studio", skip: "Bỏ qua menu, đến nội dung" },
};
