import { home } from './home';
import { homeEn } from './home-en';
export type Locale = 'vi' | 'en';
export const getHome = (locale: Locale) => locale === 'en' ? homeEn : home;
export const localePath = (locale: Locale) => locale === 'en' ? '/en' : '/';
export const interfaceCopy = {
  vi: { explore: 'Khám phá cách học', reassurance: 'Bắt đầu đơn giản. Sáng tạo theo cách của bạn.', start: 'Bắt đầu với workshop miễn phí', prompt: 'Không cần câu lệnh phức tạp. Bắt đầu bằng điều bạn hình dung.', imageAlt: 'Khung hình minh hoạ AI: người đứng giữa núi rừng Việt Nam lúc bình minh', firstStep: 'Thử bước đầu tiên', top: 'GenYZ Studio — về đầu trang', navigation: 'Điều hướng chính', mobileNavigation: 'Điều hướng trên điện thoại', contact: 'Liên hệ', open: 'Mở menu', close: 'Đóng menu', gallery: 'Thư viện phim của GenYZ Studio', previous: 'Video trước', next: 'Video tiếp theo', choose: 'Chọn phim', chooseVideo: 'Chọn video', watch: 'Xem trên', load: 'Mở video', closePlayer: 'Đóng trình phát', playerHint: 'Nhấn mở video để tải trình phát', note: 'Sản phẩm của studio, không phải kết quả học viên hay cam kết đầu ra. Nhấn mở video để tải trình phát YouTube hoặc TikTok. Nếu video không phát, bạn có thể xem trực tiếp trên nền tảng.' },
  en: { explore: 'Explore the learning path', reassurance: 'Start simple. Create in your own way.', start: 'Start with the free workshop', prompt: 'No complicated prompt needed. Start with what you imagine.', imageAlt: 'AI illustration: a person in the mountains of Vietnam at sunrise', firstStep: 'Try the first step', top: 'GenYZ Studio — back to top', navigation: 'Main navigation', mobileNavigation: 'Mobile navigation', contact: 'Contact', open: 'Open menu', close: 'Close menu', gallery: 'GenYZ Studio film gallery', previous: 'Previous video', next: 'Next video', choose: 'Choose a film', chooseVideo: 'Choose video', watch: 'Watch on', load: 'Play video', closePlayer: 'Close player', playerHint: 'Select play to load the player from', note: 'Studio productions, not student work or promised workshop outcomes. Select play to load YouTube or TikTok. If playback is unavailable, watch directly on the platform.' }
};
