import type { Locale } from './locales';
import type { StageId, WorkflowProject } from './workflows';

export const pipelineIds = ['story', 'references', 'planning', 'frames', 'motion', 'review', 'edit', 'sound', 'delivery'] as const;
export type PipelineId = typeof pipelineIds[number];
type Translation = readonly [string, string];
interface StepDefinition { id: PipelineId; phase: number; title: Translation; action: Translation; output: Translation; check: Translation }
const definitions: StepDefinition[] = [
  { id:'story', phase:0, title:['Story & intention','Câu chuyện & cảm xúc'], action:['Define the audience, story beats and the feeling each scene should create. Set the duration and delivery format before generating.','Xác định người xem, nhịp truyện và cảm xúc của từng cảnh. Chốt thời lượng và định dạng trước khi tạo hình.'], output:['Creative brief, script and scene goals','Đề bài sáng tạo, kịch bản và mục tiêu từng cảnh'], check:['Does every scene move the story forward?','Mỗi cảnh có giúp câu chuyện tiến triển không?'] },
  { id:'references', phase:0, title:['Visual references','Tham chiếu hình ảnh'], action:['Establish characters, wardrobe, props, locations, palette and lighting in a shared visual guide. AI references can replace building a complete 3D asset library for every film.','Chốt nhân vật, trang phục, đạo cụ, bối cảnh, màu sắc và ánh sáng trong bộ hướng dẫn hình ảnh. Ảnh tham chiếu giúp giảm nhu cầu dựng toàn bộ thư viện tài sản 3D.'], output:['Character and world reference sheets','Bộ tham chiếu nhân vật và thế giới'], check:['Are identity, scale and visual style consistent?','Nhận diện, tỷ lệ và phong cách có nhất quán không?'] },
  { id:'planning', phase:0, title:['Storyboard & shot plan','Storyboard & kế hoạch cảnh'], action:['Choose framing, action, camera direction and timing for each shot. Use a rough animatic or 3D blocking when timing or spatial relationships need testing.','Chọn bố cục, hành động, hướng máy và thời lượng từng shot. Dùng animatic thô hoặc dựng khối 3D khi cần thử nhịp hay quan hệ không gian.'], output:['Ordered storyboard and shot list; optional timing study','Storyboard theo thứ tự và danh sách shot; bản thử nhịp khi cần'], check:['Do the cuts, screen direction and emotional progression make sense?','Nhịp cắt, hướng chuyển động và diễn biến cảm xúc có hợp lý không?'] },
  { id:'frames', phase:1, title:['Build the shot frames','Tạo khung hình cho shot'], action:['Bring the approved references into each composition. Refine the start frame and, where useful, an end frame before spending on motion generation.','Đưa tham chiếu đã chốt vào bố cục từng shot. Chỉnh khung đầu và khung cuối khi cần trước khi tạo chuyển động.'], output:['Selected shot frames and their reference inputs','Khung hình đã chọn và ảnh tham chiếu đầu vào'], check:['Check faces, hands, props, scale, composition and lighting before animation.','Kiểm tra mặt, tay, đạo cụ, tỷ lệ, bố cục và ánh sáng trước khi tạo chuyển động.'] },
  { id:'motion', phase:1, title:['Direct & generate motion','Đạo diễn & tạo chuyển động'], action:['Describe the subject action, camera movement and duration shot by shot. Generate takes from the chosen frames; keep the camera instruction clear and purposeful.','Mô tả hành động, chuyển động máy và thời lượng cho từng shot. Tạo các take từ khung hình đã chọn; chỉ dẫn máy quay rõ ràng và có mục đích.'], output:['Generated takes with prompts and settings','Các take cùng prompt và thiết lập'], check:['Does the action read clearly without identity or geometry drifting?','Hành động có rõ ràng, không sai nhận diện hay biến dạng không?'] },
  { id:'review', phase:1, title:['Review & retake','Duyệt & tạo lại'], action:['Compare takes against the script and references. Keep the usable section, record problems and return to the frame or motion prompt when a shot fails.','So sánh các take với kịch bản và tham chiếu. Chọn đoạn dùng được, ghi lỗi và quay lại sửa khung hình hoặc prompt chuyển động khi cần.'], output:['Selected takes, usable ranges and a retake list','Take đã chọn, đoạn dùng được và danh sách cần tạo lại'], check:['Review continuity, performance, dialogue timing and unwanted visual changes.','Kiểm tra tính liên tục, diễn xuất, nhịp thoại và thay đổi hình ảnh ngoài ý muốn.'] },
  { id:'edit', phase:2, title:['Assemble & shape rhythm','Dựng phim & tạo nhịp'], action:['Arrange the selected takes, trim weak boundaries and build the scene rhythm. Use compositing, repairs or graphics only where the story needs them.','Sắp xếp take đã chọn, cắt bỏ đầu cuối chưa tốt và tạo nhịp cảnh. Ghép lớp, sửa hình hoặc thêm đồ hoạ khi câu chuyện cần.'], output:['Picture edit with purposeful cuts','Bản dựng hình với nhịp cắt có chủ đích'], check:['Can viewers follow the story when the shots are watched together?','Người xem có theo được câu chuyện khi các shot nối với nhau không?'] },
  { id:'sound', phase:2, title:['Voice, ambience & music','Thoại, không gian & nhạc'], action:['Balance dialogue with ambience, action sounds and music. Sound can begin during planning and continues through the final mix.','Cân bằng thoại với âm thanh không gian, tiếng động hành động và nhạc. Âm thanh có thể bắt đầu từ khâu lên ý tưởng và được hoàn thiện ở bản phối cuối.'], output:['Synchronized sound and a balanced mix','Âm thanh đồng bộ và bản phối cân bằng'], check:['Is speech intelligible, and does sound support rather than overpower the scene?','Lời thoại có rõ, âm thanh có hỗ trợ thay vì lấn át cảnh phim không?'] },
  { id:'delivery', phase:2, title:['Finish & publish','Hoàn thiện & phát hành'], action:['Match colour where needed, check the complete film and export for the destination. Check captions, credits and playback before publishing.','Cân màu khi cần, xem lại toàn bộ phim và xuất theo nền tảng. Kiểm tra phụ đề, credit và khả năng phát trước khi công bố.'], output:['Reviewed master and platform-ready film','Bản phim đã duyệt và bản xuất cho nền tảng'], check:['Watch the exported file, including its audio, from start to finish.','Xem và nghe bản xuất từ đầu đến cuối.'] },
];
export const pipelineCopy = {
  en: { title:'A film pipeline, simplified by AI.', intro:'Three phases. Nine creative steps. AI brings several technical tasks together; story, direction and editorial judgment still connect the film.', phases:['Pre-production','AI production','Post-production'], method:'How the step works', output:'What this produces', check:'Review before moving on', evidence:'Project example', missing:'Production breakdown not published', missingText:'This explains the method. We have not published project-specific evidence for this step yet.', loop:'Review is a loop: revise the references, frame or motion prompt, then generate another take.', optional:'Animatics, 3D blocking, compositing and VFX are optional techniques, chosen for the needs of a shot.', mapping:'What changes from traditional 3D?', comparison:'For image-to-video work, reference design and frame generation can combine much of modelling, texturing, lighting and rendering. Motion generation can reduce manual rigging and animation. These techniques remain useful when precise control is needed.', selected:'Pipeline for', evidenceNote:'Examples show available materials, not proof of every intermediate production step.' },
  vi: { title:'Quy trình làm phim, tinh gọn cùng AI.', intro:'Ba giai đoạn. Chín bước sáng tạo. AI kết hợp nhiều công đoạn kỹ thuật; câu chuyện, đạo diễn và quyết định dựng vẫn kết nối cả bộ phim.', phases:['Tiền kỳ','Sản xuất với AI','Hậu kỳ'], method:'Cách thực hiện', output:'Đầu ra của bước này', check:'Kiểm tra trước khi đi tiếp', evidence:'Ví dụ từ dự án', missing:'Chưa công bố tư liệu quy trình', missingText:'Đây là phần giải thích phương pháp. Tư liệu riêng của dự án cho bước này chưa được công bố.', loop:'Duyệt là một vòng lặp: sửa tham chiếu, khung hình hoặc prompt chuyển động, rồi tạo take mới.', optional:'Animatic, dựng khối 3D, ghép lớp và VFX là kỹ thuật tuỳ chọn theo nhu cầu từng shot.', mapping:'Điều gì thay đổi so với 3D truyền thống?', comparison:'Với quy trình từ ảnh sang video, thiết kế tham chiếu và tạo khung hình có thể kết hợp phần lớn công việc dựng hình, vật liệu, ánh sáng và render. Tạo chuyển động giúp giảm thao tác rig và animation thủ công. Những kỹ thuật này vẫn hữu ích khi cần kiểm soát chính xác.', selected:'Quy trình của', evidenceNote:'Ví dụ thể hiện tư liệu hiện có, không xác nhận mọi bước trung gian của quá trình sản xuất.' },
};
export function getPipeline(locale: Locale) {
  const index = locale === 'en' ? 0 : 1;
  return definitions.map(step => ({ ...step, title:step.title[index], action:step.action[index], output:step.output[index], check:step.check[index] }));
}

/** Only link to materials actually represented in the public project archive. */
export function getPipelineEvidence(project: WorkflowProject, id: PipelineId, locale: Locale = 'en') {
  if (id === 'frames' || id === 'review' || id === 'edit' || id === 'sound') {
    const evidence = project.pipelineEvidence?.[id];
    if (evidence) return evidence;
  }
  const en = locale === 'en';
  const film = project.stages.film;
  if (id === 'edit' && film && ['great-gulp', 'little-rat'].includes(project.id)) return {
    ...film,
    title: en ? 'See the assembled film.' : 'Xem các cảnh kết nối thành phim.',
    text: en ? 'The published film shows the assembled result. An editing timeline and before-and-after cut comparison are not published here.' : 'Phim đã phát hành thể hiện kết quả dựng hoàn chỉnh. Timeline dựng và so sánh trước/sau chưa được công bố tại đây.',
  };
  if (id === 'sound' && film && project.id === 'great-gulp') return {
    ...film,
    title: en ? 'Listen to the finished mix.' : 'Nghe bản phối hoàn chỉnh.',
    text: en ? 'The Great Gulp archive contains a barnyard score, evening ambience and a final music-mix export. Listen to the published film; the separate audio stems and mixing timeline are not embedded here.' : 'Kho tư liệu Great Gulp có nhạc nền nông trại, âm thanh chiều tối và bản xuất phối nhạc cuối. Nghe trong phim đã phát hành; các lớp âm thanh riêng và timeline phối chưa được nhúng tại đây.',
    lesson: en ? 'Listen for how dialogue, background atmosphere and music share the scene.' : 'Lắng nghe cách thoại, âm thanh không gian và nhạc cùng phục vụ cảnh phim.',
  };
  const stageMap: Partial<Record<PipelineId, StageId>> = { story:'story', references:'characters', planning:'storyboard', motion:'motion', delivery:'film' };
  const stageId = stageMap[id];
  return stageId ? project.stages[stageId] : undefined;
}
