import type { Locale } from './locales';

export const greatGulp = {
  title: "The Great Gulp and the Cock-A-Doodle-Don't",
  url: 'https://www.youtube.com/watch?v=MsXyfqlA1Fw',
  poster: '/images/great-gulp/film-poster.webp',
  preview: '/videos/great-gulp/sunset-excerpt.mp4',
};

const vi = {
  eyebrow: 'AI VIDEO STUDIO & ĐÀO TẠO',
  title: 'Từ ý tưởng.\nĐến thước phim.',
  description: 'Studio sản xuất video AI và hướng dẫn bạn tự kể chuyện bằng ngôn ngữ điện ảnh.',
  work: 'Xem phim', learn: 'Học làm phim', contact: 'Trao đổi dự án',
  heroCaption: 'The Great Gulp · Phim hoạt hình của GenYZ Studio',
  pathsTitle: 'Cùng làm phim. Cùng học cách kể chuyện.',
  studioTitle: 'Bạn có câu chuyện.\nCùng chúng tôi đưa lên màn ảnh.',
  studioDescription: 'Trao đổi về phim hoạt hình, câu chuyện thương hiệu hoặc video cho kênh của bạn. Bắt đầu từ ý tưởng, đối tượng xem và cảm xúc bạn muốn để lại.',
  studioTags: ['Phát triển ý tưởng', 'Nhân vật & thế giới', 'Sản xuất & hậu kỳ'],
  trainingTitle: 'Bạn muốn tự làm.\nBắt đầu cùng studio.',
  trainingDescription: 'Học từ những quyết định thật trong phim của studio. Viết câu chuyện, chọn góc máy, giữ nhân vật nhất quán và dựng từng cảnh thành một mạch kể.',
  trainingTags: ['Dành cho người mới', 'Hướng dẫn tiếng Việt', 'Thực hành có hướng dẫn'],
  caseLabel: 'CÂU CHUYỆN ĐẰNG SAU BỘ PHIM',
  caseTitle: 'Một chú heo thư thái.\nMột chú gà luôn vội.',
  caseDescription: 'Barnaby chỉ muốn thưởng thức bữa trưa. Hildebrand muốn mọi thứ đúng lịch. Khi kho ngô bung cửa, một ngày hỗn loạn trở thành câu chuyện về tình bạn.',
  format: 'Phim hoạt hình AI', duration: '3 phút 58 giây', frames: '28 khung storyboard',
  chaptersTitle: 'Cảm xúc dẫn đường cho từng cảnh.',
  chaptersDescription: 'Khám phá ba nhịp truyện qua khung storyboard gốc, rồi xem chúng chuyển thành phim.',
  storyboard: 'Khung storyboard gốc',
  chapters: [
    { name: 'Hai tính cách đối lập', title: 'Cho khán giả một lý do để quan tâm.', text: 'Một hạt đậu bé xíu và một lịch trình kín mít giới thiệu hai nhân vật. Sự chậm rãi của Barnaby đối lập với vẻ tất bật của Hildebrand, tạo tiếng cười trước khi rắc rối bắt đầu.', lesson: 'Bài học: thể hiện tính cách bằng hành động và đạo cụ.', image: '/images/great-gulp/setup.webp', alt: 'Barnaby và Hildebrand đối diện nhau bên gốc cây dùng làm bàn ăn.' },
    { name: 'Mọi kế hoạch đổ vỡ', title: 'Đẩy mâu thuẫn thành hành động.', text: 'Cơn thèm ăn của Barnaby dẫn cả hai đến kho ngô. Hildebrand cố kéo bạn ra, nhưng cánh cửa bật tung. Đợt sóng ngô biến khác biệt tính cách thành một tình huống hài hình thể.', lesson: 'Bài học: để mỗi hành động dẫn đến một hệ quả.', image: '/images/great-gulp/chaos.webp', alt: 'Một làn sóng ngô tràn khỏi kho, cuốn lấy Barnaby và Hildebrand.' },
    { name: 'Một khoảnh khắc lắng lại', title: 'Kết bằng sự thay đổi của nhân vật.', text: 'Giữa đống ngô, Barnaby nhắc bạn nhìn lên hoàng hôn. Hildebrand dần buông lịch trình. Chiếc bảng trống ở cảnh cuối cho thấy cậu đã học cách tận hưởng một ngày không theo kế hoạch.', lesson: 'Bài học: dùng ánh sáng, nhịp dựng và chi tiết để khép lại cảm xúc.', image: '/images/great-gulp/sunset.webp', alt: 'Barnaby đặt chân lên cánh Hildebrand trong ánh hoàng hôn ấm áp.' },
  ],
  characters: 'Xem thiết kế hai nhân vật',
  barnaby: 'Barnaby · Thư thái, ham ăn và luôn sống cho hiện tại.',
  hildebrand: 'Hildebrand · Tận tâm, sốt ruột và không rời chiếc bảng lịch trình.',
  reference: 'Ảnh tham chiếu nhân vật từ dự án gốc.',
  bridgeTitle: 'Từ xem một bộ phim\nđến hiểu cách làm ra nó.',
  bridgeText: 'Đây cũng là cách chúng tôi tiếp cận đào tạo: bắt đầu bằng câu chuyện, rồi chọn công cụ phục vụ từng cảnh. Workshop nhập môn giúp bạn thử bước đầu tiên.',
  notebook: 'Khám phá thêm quy trình trong studio',
  galleryTitle: 'Những thế giới khác của GenYZ.',
  galleryDescription: 'Từ cuộc phiêu lưu tí hon đến những câu chuyện hoạt hình. Chọn một phim để khám phá.',
  contactTitle: 'Câu chuyện tiếp theo\nbắt đầu cùng bạn.',
  contactDescription: 'Bạn muốn sản xuất video hay tìm hiểu chương trình học? Hãy kể cho chúng tôi ý tưởng và mục tiêu của bạn.',
  projectEmail: 'Gửi ý tưởng qua email',
};

const en: typeof vi = {
  eyebrow: 'AI VIDEO STUDIO & FILMMAKING TRAINING',
  title: 'An idea today.\nA film tomorrow.',
  description: 'We create AI films and teach you the craft behind them. Your story is where it starts.',
  work: 'Watch our films', learn: 'Learn filmmaking', contact: 'Start a project',
  heroCaption: 'The Great Gulp · An animated film by GenYZ Studio',
  pathsTitle: 'A studio to create with. A place to learn.',
  studioTitle: 'Bring your story.\nLet’s bring it to the screen.',
  studioDescription: 'Talk to us about an animated film, a brand story or a video for your channel. We start with your idea, your audience and what you want them to feel.',
  studioTags: ['Story development', 'Characters & worlds', 'Production & editing'],
  trainingTitle: 'Want to make it yourself?\nStart here, with us.',
  trainingDescription: 'Learn from the creative decisions in our films. Shape a story, choose your shots, keep characters consistent and edit individual scenes into a film.',
  trainingTags: ['Beginner friendly', 'Taught in Vietnamese', 'Guided practice'],
  caseLabel: 'BEHIND THE FILM',
  caseTitle: 'One laid-back pig.\nOne very busy rooster.',
  caseDescription: 'Barnaby wants to enjoy his lunch. Hildebrand wants everything on schedule. When a corn silo bursts open, a chaotic afternoon becomes a story about friendship.',
  format: 'AI animated short', duration: '3 min 58 sec', frames: '28 storyboard frames',
  chaptersTitle: 'Every shot starts with a feeling.',
  chaptersDescription: 'Explore three story beats through the original storyboard frames, then watch them come to life in the film.',
  storyboard: 'Original storyboard frame',
  chapters: [
    { name: 'Opposites, introduced', title: 'Give us someone to care about.', text: 'A tiny pea and an overflowing schedule introduce two very different friends. Barnaby’s unhurried lunch contrasts with Hildebrand’s frantic energy, building comedy before anything goes wrong.', lesson: 'The craft: reveal character through actions and props.', image: '/images/great-gulp/setup.webp', alt: 'Barnaby and Hildebrand facing each other at a tree-stump dining table.' },
    { name: 'The plan falls apart', title: 'Turn a disagreement into action.', text: 'Barnaby’s appetite leads them to the corn silo. Hildebrand tries to pull him away, but the hatch bursts open. A wave of corn turns their clashing personalities into physical comedy.', lesson: 'The craft: make each action cause the next.', image: '/images/great-gulp/chaos.webp', alt: 'A wave of golden corn bursts from the silo over Barnaby and Hildebrand.' },
    { name: 'A moment to breathe', title: 'End with a character who has changed.', text: 'On the corn mound, Barnaby asks his friend to look at the sunset. Hildebrand finally lets go of the schedule. His empty clipboard in the final scene shows that an unplanned day can be a good one.', lesson: 'The craft: use light, pacing and a small detail to land the emotion.', image: '/images/great-gulp/sunset.webp', alt: 'Barnaby rests a trotter on Hildebrand’s wing in the warm sunset light.' },
  ],
  characters: 'Explore the character designs',
  barnaby: 'Barnaby · Unhurried, food-loving and always in the moment.',
  hildebrand: 'Hildebrand · Caring, anxious and inseparable from his schedule.',
  reference: 'Character reference images from the original project.',
  bridgeTitle: 'From watching a film\nto understanding the craft.',
  bridgeText: 'That is how we approach teaching, too: start with the story, then choose tools that serve each scene. The introductory workshop lets you try the first step.',
  notebook: 'Explore more of our production process',
  galleryTitle: 'More worlds from GenYZ.',
  galleryDescription: 'Tiny adventures and animated stories. Choose a film to explore.',
  contactTitle: 'The next story\nstarts with you.',
  contactDescription: 'Looking to produce a video or learn how to make one? Tell us about your idea and what you want to achieve.',
  projectEmail: 'Send your brief by email',
};

export const studioCopy: Record<Locale, typeof vi> = { vi, en };
