import type { Locale } from './locales';
import type { WorkflowProject, WorkflowStage } from './workflows';

export function getTitusWorkflow(locale: Locale): WorkflowProject {
  const en = locale === 'en';
  const picture = (name: string, caption: string) => ({src:`/images/titus-process/${name}.webp`,alt:caption,caption});
  const film: WorkflowStage = {
    title:'The Legend of Titus',
    text:en?'A mysterious blue scale draws Titus into an adventure along the river, with Rowan, Professor Paddle and the Great Blue Glimmer.':'Một chiếc vảy xanh bí ẩn đưa Titus vào cuộc phiêu lưu dọc dòng sông, cùng Rowan, Professor Paddle và Great Blue Glimmer.',
    lesson:en?'Follow the scale as a recurring visual thread connecting characters and locations.':'Theo dõi chiếc vảy như sợi dây hình ảnh kết nối nhân vật và bối cảnh.',
    film:{title:'The Legend of Titus',description:'GenYZ Studio',platform:'YouTube',url:'https://www.youtube.com/watch?v=VzmqrgQumGo',thumbnail:'/images/titus.jpg'},
  };
  return {
    id:'titus',title:'The Legend of Titus',subtitle:en?'A river mystery, from script to screen':'Bí ẩn dòng sông, từ kịch bản đến phim',cover:'/images/titus.jpg',
    stages:{
      story:{title:en?'Let a small discovery open a larger world.':'Một phát hiện nhỏ mở ra cả thế giới.',text:en?'The six-scene script begins at sunrise. Titus notices a blue reflection, discovers a scale and follows the river’s signal. Scene 1 withholds the creature behind the mystery.':'Kịch bản sáu cảnh mở đầu lúc bình minh. Titus thấy ánh xanh, tìm được chiếc vảy và đi theo tín hiệu dòng sông. Cảnh đầu giữ kín sinh vật đứng sau bí ẩn.',quote:'Titus: “A scale… but from what?”',lesson:en?'Reveal information in stages: reflection, object, then the question it raises.':'Hé lộ từng bước: ánh phản chiếu, vật thể, rồi câu hỏi mà nó gợi ra.',media:[picture('shot-plan',en?'Scene 1, shot 4 · Discovery storyboard':'Cảnh 1, shot 4 · Storyboard phát hiện chiếc vảy')]},
      characters:{title:en?'Lock the character, place and prop together.':'Chốt nhân vật, bối cảnh và đạo cụ.',text:en?'Titus’s orange stripes, brass bell and blue ankle cord anchor his identity. The reference package also defines the river, the translucent scale and the Great Blue Glimmer.':'Vằn cam, chuông đồng và dây xanh ở cổ chân tạo nhận diện Titus. Bộ tham chiếu còn định hình dòng sông, chiếc vảy trong suốt và Great Blue Glimmer.',lesson:en?'Continuity depends on recurring props and geography as well as faces.':'Tính liên tục còn nằm ở đạo cụ và địa hình, không chỉ khuôn mặt.',media:[picture('character',en?'Titus · Character reference':'Titus · Tham chiếu nhân vật'),picture('glimmer',en?'Great Blue Glimmer · Character reference':'Great Blue Glimmer · Tham chiếu nhân vật'),picture('location',en?'Riverside · Location reference':'Bờ sông · Tham chiếu bối cảnh'),picture('scale',en?'Blue scale · Prop reference':'Vảy xanh · Tham chiếu đạo cụ')]},
      storyboard:{title:en?'Give each shot a production plan.':'Mỗi shot có một kế hoạch sản xuất.',text:en?'The scene 1, shot 4 dashboard combines character views, location geography, four timed panels, camera notes and sound direction. The Flow prompt pack adds explicit visual handoffs between shots.':'Bảng cảnh 1, shot 4 kết hợp góc nhìn nhân vật, địa hình, bốn khung có thời lượng, ghi chú máy quay và âm thanh. Bộ prompt Flow bổ sung điểm nối hình ảnh giữa các shot.',lesson:en?'A storyboard should communicate what stays consistent and how the next shot begins.':'Storyboard cần chỉ rõ điều phải giữ nhất quán và cách shot tiếp theo bắt đầu.',media:[picture('shot-plan',en?'Original storyboard · Scene 1, shot 4':'Storyboard gốc · Cảnh 1, shot 4')]},
      motion:{title:en?'Compare the planned discovery with a generated shot.':'So sánh kế hoạch với cảnh tạo chuyển động.',text:en?'This silent excerpt comes from S1-04 in the OpenArt download archive. Compare the scale reveal and camera framing with the shot dashboard. The archive does not establish which exact inputs generated this take.':'Trích đoạn không tiếng từ S1-04 trong kho tải OpenArt. So sánh cách hé lộ chiếc vảy và bố cục với bảng cảnh. Kho tư liệu chưa xác nhận chính xác các đầu vào đã tạo take này.',lesson:en?'Judge whether the movement preserves the planned reveal and character identity.':'Đánh giá chuyển động có giữ đúng nhịp hé lộ và nhận diện nhân vật không.',media:[{src:'/media/titus/scene-01-shot-04.mp4',poster:'/images/titus-process/motion.webp',alt:en?'Titus discovers the blue scale':'Titus phát hiện chiếc vảy xanh',caption:en?'Scene 1, shot 4 · Silent production excerpt':'Cảnh 1, shot 4 · Trích đoạn sản xuất không tiếng'}]},
      film,
    },
    pipelineEvidence:{
      frames:{title:en?'Inspect the individual storyboard panels.':'Xem từng khung storyboard.',text:en?'Scene 2, shot 4 has four separate cut panels showing Rowan studying the scale. These are labelled storyboard panels, not verified clean start/end frames submitted to a video generator.':'Cảnh 2, shot 4 có bốn khung riêng khi Rowan nghiên cứu chiếc vảy. Đây là khung storyboard có nhãn, chưa được xác nhận là ảnh đầu/cuối sạch đã gửi vào công cụ tạo video.',lesson:en?'Separate planning panels from generation-ready inputs; remove layout labels before preparing a clean frame.':'Phân biệt khung lên kế hoạch với ảnh đầu vào; loại bỏ nhãn bố cục khi chuẩn bị khung sạch.',media:[1,2,3,4].map(i=>picture(`cut-${i}`,en?`Scene 2, shot 4 · Storyboard panel ${i}`:`Cảnh 2, shot 4 · Khung storyboard ${i}`))},
      edit:{title:en?'Give the film a deliberate ending.':'Khép lại bộ phim có chủ đích.',text:en?'The repository includes a standalone ending-credits render. This 12-second silent excerpt illustrates a finishing asset; the full editing timeline and its inclusion in the published film have not been verified.':'Kho tư liệu có bản render credit cuối phim riêng. Trích đoạn không tiếng 12 giây minh hoạ tài sản hoàn thiện; chưa xác minh timeline dựng đầy đủ hay việc đưa bản credit này vào phim đã phát hành.',lesson:en?'Review titles and credits as part of the viewing experience, alongside the picture edit.':'Duyệt tiêu đề và credit như một phần trải nghiệm xem, cùng với bản dựng hình.',media:[{src:'/media/titus/credits.mp4',poster:'/images/titus-process/credits.webp',alt:en?'Titus ending-credits excerpt':'Trích đoạn credit cuối Titus',caption:en?'Standalone ending-credits asset · 12 seconds':'Tài sản credit cuối riêng · 12 giây'}]},
      sound:{title:en?'Hear the source and separated voice.':'Nghe âm thanh gốc và giọng đã tách.',text:en?'Scene 1, shot 3 includes an extracted source track and a voice-only version. Compare these short samples. Separation may leave artefacts; these are intermediate audio assets, not isolated stems from the final mix.':'Cảnh 1, shot 3 có âm thanh trích xuất và bản tách giọng. So sánh hai mẫu ngắn. Tách giọng có thể còn nhiễu; đây là tài sản âm thanh trung gian, không phải các lớp tách từ bản phối cuối.',lesson:en?'Check speech clarity and residual noise before placing a separated track into the edit.':'Kiểm tra độ rõ lời thoại và nhiễu còn lại trước khi đưa bản tách vào phim.',audio:[{src:'/media/titus/source-audio.mp3',label:en?'Source audio · Scene 1, shot 3':'Âm thanh gốc · Cảnh 1, shot 3'},{src:'/media/titus/isolated-voice.mp3',label:en?'Separated voice · Same shot':'Giọng đã tách · Cùng shot'}]},
    },
  };
}
